### ISSUE TITLE
Refresh Tokens

### ISSUE THREAD

**Issue by brayniverse** [oauth-io/oauth-js#19]
I am trying to get access tokens for any Google based provider however whenever I authenticate I get an `access_token` but no `refresh_token`. I have chosen `offline` for the `access_type` but still no joy.

Am I being a moron? I have tried looking through the documentation for a solution but it barely covers anything related to the refresh token.

**Comment by angelxmoreno** [comment]
@brayniverse is your problem is resolved please close this ticket
