### ISSUE TITLE
oauthio_provider_* cookie should set secure flag if site is https

### ISSUE THREAD

**Issue by nodesocket** [oauth-io/oauth-js#29]
Is it possible to set the **secure** flag (https://www.owasp.org/index.php/SecureFlag) on the `oauthio_provider_* ` cookie when the site is served over https? Maybe have this be an option, if you don't want to automatically detect if https or not.

**Comment by angelxmoreno** [comment]
:+1:

**Comment by angelxmoreno** [comment]
@nodesocket not sure if you already addressed this but if you did, a PR would be great. I do not know coffee-script but here is the cookie module code https://github.com/oauth-io/oauth-js/blob/master/coffee/tools/cookies.coffee

**Comment by bumpmann** [comment]
These cookies were not meant to be sent in http requests but for cache, so it now uses the local storage if possible. Setting the secure flags makes it unreadable in JS, that why it was a not so good solution.
