### ISSUE TITLE
Paypal Create payment throws HTTP Status 415: Unsupported Media Type

### ISSUE THREAD

**Issue by nmehta6** [oauth-io/oauth-js#30]
I am trying to make the following call to Paypal's REST API. I am getting HTTP Status code 415 in response. This happens when making the api call to the url '/v1/payments/payment'. It seems like the HTTP header is incorrectly sent? I am not entirely sure. I did not see any documentation that the result object allows setting HTTP headers. Please help. Thanks.

```
OAuth.initialize('myoauthiotoken');

OAuth.popup('paypal').done((function(_this) {
  return function(result) {
    console.log('result', result);
    return result.post({
      url: '/v1/payments/payment',
      data: {
        intent: 'sale',
        payer: {
          payment_method: 'paypal'
        },
        transactions: [
          {
            amount: {
              currency: 'USD',
              total: '5.69'
            }
          }
        ],
        redirect_urls: {
          return_url: 'https://oauth.io/auth',
          cancel_url: 'https://oauth.io/auth'
        }
      }
    }).done(function(response) {
      return console.log('payment response', response);
    });
  };
})(this));
```

**Comment by bumpmann** [comment]
This issue is old and i didn't notice problems with paypal. There was missing the body data to be passed as string with `JSON.stringify`. Please reopen if you still have the problem.
