### ISSUE TITLE
Bower main property update

### ISSUE THREAD

**Issue by brutalhonesty** [oauth-io/oauth-js#38]
https://github.com/bower/bower.json-spec requests ```main``` property files to be non-minified. Please update ```bower.json``` to use ```dist/oauth.js``` instead of ```dist/oauth.min.js``` for the main property.

As a temporary work-around, for people who have [grunt-wiredep](https://github.com/stephenplusplus/grunt-wiredep), you can add an ```overrides``` object to your package's ```bower.json``` file. An example would be:

```javascript
// bower.json
"overrides": {
  "oauth-js": {
    "main": ["dist/oauth.js"]
  }
}
```

**Comment by bumpmann** [comment]
Thanks
