### ISSUE TITLE
Trouble with require.js and minimized js

### ISSUE THREAD

**Issue by donbrad** [oauth-io/oauth-js#39]
Hi,

oauthio is working fine in my app in production mode.   after all the js files are concatted and minimized in to single file (DesktopInit.min.js).  I get the following error:

Uncaught TypeError: undefined is not a function DesktopInit.min.js:1./lib/oauth DesktopInit.min.js:1i DesktopInit.min.js:1e DesktopInit.min.js:1(anonymous function) DesktopInit.min.js:1(anonymous function) DesktopInit.min.js:1(anonymous function) DesktopInit.min.js:1

![developer_tools_-_http___localhost_8001_](https://cloud.githubusercontent.com/assets/609187/4852851/0edf9f24-6080-11e4-893b-12608e7289c5.png)

Any ideas?

**Comment by brutalhonesty** [comment]
I'm also have a similar issue with my concatted/minified code. Digging into the issue, it seems that the non-minified code is in fact slightly minified which might be causing issues for people with task runners which minify their own and vendors code.

Taking a look into the Gruntfile.js for this project, it appears that when the coffeescript is converted to javascript, there is an uglify task which mangles the variables.

https://github.com/oauth-io/oauth-js/blob/master/Gruntfile.js#L56

I believe to fix the non-minified file, you can simply use the following for that task:

```javascript
```
