### ISSUE TITLE
Can't post exclamation mark to twitter

### ISSUE THREAD

**Issue by queile** [oauth-io/oauth-js#40]
```javascript
result.post('/1.1/statuses/update.json', {
      data: {
        status: '!'
      }
    }).done(function(json){
    });
```
This code results  "Could not authenticate you" error (code=32)
It's probably because Twitter API 1.1 requires escaping characters :! ( ) ' *

So I replaced encodeURIComponent() with fixedEncodeURIComponent() in oauth.js
```javascript
function fixedfixedEncodeURIComponent (str) {
  return fixedEncodeURIComponent(str).replace(/[!'()]/g, escape).replace(/\*/g, "%2A");
}
```
But the result is same. Is this server-side problem?

**Comment by bumpmann** [comment]
It has been fixed with the https://github.com/oauth-io/oauthd-request/commit/bf0798bc5877a12e27e5ff97fe94b4ce32f156dd commit on oauthd-request.
