### ISSUE TITLE
missing semicolon breaks minification with other modules

### ISSUE THREAD

**Issue by jameyquinn** [oauth-io/oauth-js#41]
oauth-js/dist contains both an expanded and a minified version of the js source. When minifying the expanded version with other unrelated packages, the lack of a semicolon prevents a comma break from being placed properly. if using the minified version - which contains the semicolon - all proceeds as expected.

**Comment by grammka** [comment]
Check this....

**Comment by jeffthompson1971** [comment]
any solution to this?  i'm seeing breakage in my app when the 'uglification' happens, and it happens only on the very first line where oauth.io is getting concat-ed to my uglified scripts.js file.     I put a semicolon at the very beginning and it seemed to get past that error.    what's the correct solution?
