### ISSUE TITLE
Is oauth.js available as something Angular injectible?

### ISSUE THREAD

**Issue by kalanbates** [oauth-io/oauth-js#42]
Is oauth.js available as an Angular Factory, directive, etc?
It needs to be.

**Comment by angelxmoreno** [comment]
@william26 I see some checks for angular already made it to master. where can I find docs to use it?

**Comment by thyb** [comment]
It hasn't been documented yet. You can inject OAuth and User variable in your controllers / services, e.g.

```
angular.module('testApp', ['oauthio']).controller('TestCtrl', function($scope, OAuth, User) {
   OAuth.initialize('xxx')
   $scope.signinClick = function(provider) {
      OAuth.popup(provider).then(function(result) {
         return User.signin(res)
      }).then(function(user) {
         //todo once logged in
      }).fail(function(err) {
         //todo with `err`
      })
   }
})
```

**Comment by LeonardoGentile** [comment]
Did this eve happened? Is there any doc on the topic?

**Comment by angelxmoreno** [comment]
It did happen. I don't think i saw docs. I just read the code. I could add docs this weekend if a PR is needed.
