### ISSUE TITLE
500 error for .me() method with GitHub

### ISSUE THREAD

**Issue by lavelle** [oauth-io/oauth-js#44]
I get a 500 server error when calling the `.me()` method with a result object obtained from `Oauth.create`. It works fine logging in directly with `Oauth.popup`. 

Code:

```js
result = OAuth.create('github', { access_token: 'TOKEN'});
result.me()
    .done(function(user) {
        console.log(user);
    })
    .fail(function(error) {
      console.error(error);
    });
```

The fail callback is triggered but `error` is undefined so there's not much I can do to diagnose the problem.

**Comment by angelxmoreno** [comment]
@lavelle did you get this working?

**Comment by bumpmann** [comment]
I tested with several use case and did not get that error. I m closing the issue but feel free to reopen it if you still have the bug

**Comment by angelxmoreno** [comment]
:+1:
