### ISSUE TITLE
Oauth-js is incompatible with Javascript libraries which extend Array.prototype

### ISSUE THREAD

**Issue by antoniozzo** [oauth-io/oauth-js#45]
When using "for...in" loops with Javascript libraries which extends the Array.prototype, prototype properties are passed as keys and breaks Oauth.js.

For example:

On line 765...

    for (k in extended_methods) {
        v = extended_methods[k];
        name_array = v.name.split('.');
        ...
    }

and line 456...

    for (k in client_states) {
        v = client_states[k];
        client_states[k] = v.replace(/\s+/g, "");
    }

In these cases "v" is sometimes an extended Array.prototype property.

See explanation/solution:
http://stackoverflow.com/a/500531

Found while using oauth-js with ember-js.

**Comment by railsjedi** [comment]
patch doesn't apply cleanly to 0.4.0 (or master), but it fixes my problem when i apply it manually

this issues should really be taken care of, it's sure to continue wasting lot of dev's time

**Comment by antoniozzo** [comment]
This was a patch for 0.3.0 (at the time i did it).
But yes, it should be taken care of!

**Comment by railsjedi** [comment]
cool. thanks for the help!
