### ISSUE TITLE
Twitter authentication breaks with `undefined` in place of String value

### ISSUE THREAD

**Issue by fzero** [oauth-io/oauth-js#47]
I've just found this bug while trying Oauth.io. The quickfix was simply to typecast the value with `String()` in the /dist JS code but you'll probably want to port it to your CoffeeScript source.

The issue is at https://github.com/oauth-io/oauth-js/blob/master/dist/oauth.js#L767

I fixed it locally changing it from:
```
client_states[k] = v.replace(/\s+/g, "");
```
to:
```
client_states[k] = String(v).replace(/\s+/g, "");
```

**Comment by zachelrath** [comment]
I experienced this as well with other authentication providers --- workaround by @fzero worked for me.
