### ISSUE TITLE
any way to set cache expiry time?

### ISSUE THREAD

**Issue by fantapop** [oauth-io/oauth-js#50]
I see that there is an option cache.expires_in that appears to accepted from the oauth callback.  Is there a way to set that on the client side?  Or is this something that the provider must pass back along with the callback?

**Comment by bumpmann** [comment]
The expiration time is generally passed from the provider's response, but I added an "expires" option to `OAuth.initialize` to set the default expiration time.

```
OAuth.initialize("xxxxx", { expires: 3600*5 });
//=> set the default expiration time at 5h

OAuth.initialize("xxxxx", { expires: false });
//=> set the default expiration time at 3 years
```

There's a default cache expire time at 1h but if there is a `expires_in` field in the provider's response, it will override the default value.
