### ISSUE TITLE
require statements breaking browserify

### ISSUE THREAD

**Issue by jdiver** [oauth-io/oauth-js#51]
The odd require statements found in oauth.js are breaking browserify, as it sees them as modules to include and they don't actually exist. Lines 66-74:

    config = require('../config');

    Url = require("../tools/url");

    Location = require('../tools/location_operations');

    cookies = require("../tools/cookies");

    cache = require("../tools/cache");

**Comment by adjohnson916** [comment]
+1 I can't get it to work with browserify either.
