### ISSUE TITLE
Cannot read property 'done' of undefined in redirection mode

### ISSUE THREAD

**Issue by fgrs** [oauth-io/oauth-js#59]
I wanted to use callback instead of popup but I'm getting this error is this intentional?

**Comment by hirako2000** [comment]
Same issue here, following the documentation this approach doesn't seem to work.
For a lib that is meant to get OAuth to "just work" that's a bit troublesome.

**Comment by hirako2000** [comment]
@fgrs  I don't think it's an issue. The doc doesn't explain but it appears that OAuth.redirect() need to be invoked prior to invoking callback, otherwise *done()* is still undefined.

It sort of forces a redirect, not too sure why.

```
OAuth.redirect('google', 'http://localhost/callback');
// only then, invoke callback
```

**Comment by angelxmoreno** [comment]
just got here with the same issue. Are the docs on github or someplace where the community can edit it? I was wracking my head trying to figure this out.

**Comment by angelxmoreno** [comment]
Also, I a working on a SPA, how can i detect that there was already a redirect set in motion so that I do not call `callback()`

**Comment by angelxmoreno** [comment]
hey @hirako2000 Apparently, after further testing, I found out that this is not the case for when using the callback signature ( also not documented ). Basically:
```js
//in your callback page (can be the same page)
OAuth.callback('google').done(function(google) {
  //make API calls with `google`
}).fail(function(err) {
  //todo when the OAuth flow failed
})
```
will return an error about `callback()` not having a property of `done`. However:

```js
//in your callback page (can be the same page)
OAuth.callback('google', function(err, google) {
    //todo when the OAuth flow failed
    if(err) return handleError(err);
    //make API calls with `google`
})
```
works just fine :-1: 
It definitely smells like a bug.

**Comment by angelxmoreno** [comment]
Ok, found the culprit and a workaround.

Looks like [This line](https://github.com/oauth-io/oauth-js/blob/master/dist/oauth.js#L441) is failing to make use of the promise as a result of the `oauth_result` object never been created. It only gets created when coming back from a redirect. Unfortunately, this object is not accessible from the `OAuth` object (from what I can see). It seems like this should check if the `defer` was created and return a reject promise as opposed to void. 

The workaround is simply but still a bit annoying:
```js
    var callback = OAuth.callback('twitter');
    if(callback){
        callback.then(function(result){
            console.log('I got a result');
        });
        
        callback.fail(function(err){
            console.log('I failed to get a result because of:'+err.message);
        });
    } else {
        console.log('Currently not coming from a redirect');
    }
```

**Comment by thyb** [comment]
Thanks a lot for the investigation @angelxmoreno, we've already faced this issue but we didn't really know how to make it more simple that the workaround you've explained.

The issue is when you're not redirected by a provider, there is no reason to go in the `then()` or in the `fail()` promise as there is no callback yet. Maybe the best solution would be to return a promise but never call the success/reject method. What do you think about it? (It could be odd to declare a promise and never enter in the `then()` or `fail()` callback)

**Comment by angelxmoreno** [comment]
@thyb I think the best solution would be to expose some other check that would identify if the user is coming from a redirect and put the call to the callback inside of that. ie:
```js
var isRedirectFromTwitter = OAuth.isRedirect('twitter');//returns true if the redirect is from twitter
if (isRedirectFromTwitter) {
    OAuth.callback('twitter').then(function (result) {
        console.log('I got a result from Twitter');
    }).fail(function (err) {
        console.log('I failed to get a result from Twitter because of:' + err.message);
    });
}

var provider = OAuth.isRedirect();//returns false or a string for the provider
if (provider) {
    OAuth.callback(provider).then(function (result) {
        console.log('I got a result from ' + provider);
    }).fail(function (err) {
        console.log('I failed to get a result form ' + provider + ' because of:' + err.message);
    });
}
```
What do you think about that? 
The idea of returning a promise that has no then or fail feels like an anti-pattern

**Comment by thyb** [comment]
I agree, sounds good. The commit https://github.com/oauth-io/oauth-js/commit/5b94fdf2db3c3deb315fce3854d8cffba0872605 implement the `OAuth.isRedirect()`

```
OAuth.isRedirect(provider) 
//=> return true/false

OAuth.isRedirect() 
//=> return the provider name
```

**Comment by angelxmoreno** [comment]
:+1:
