### ISSUE TITLE
Descriptive error on origin mismatch

### ISSUE THREAD

**Issue by DomiR** [oauth-io/oauth-js#60]
On url mismatch it should probably throw an more descriptive error instead of silently failing. 

https://github.com/oauth-io/oauth-js/blob/0dbfdf1769e2b55130c6facfb18bf013ba4bb886/coffee/lib/oauth.coffee#L68

**Comment by bumpmann** [comment]
This isn't a silent fail or an error, the window can receive a lot of message from the other windows or extensions so we have to filter them.
