### ISSUE TITLE
Put it up on npm

### ISSUE THREAD

**Issue by brandonhorst** [oauth-io/oauth-js#61]
Developing client-side JS using npm (with Browserify, etc...) is a common workflow. Could an NPM package be added?

**Comment by smilledge** [comment]
Yeah, I haven't used bower in ages.

+100

**Comment by dcrockwell** [comment]
Yes. +1

**Comment by Zoltu** [comment]
:+1:

**Comment by thyb** [comment]
We've just released the new version 0.4.4 on npm

    npm install oauthio-web
