### ISSUE TITLE
Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by fo747** [oauth-io/oauth-js#74]
Am using the Node SDK with Twitter as provider. This error occurs when users select "Cancel" and then "Return to [app]" on the page where Twitter asks the user to input username and password. Instead of sending the user back, it crashes with a server error.

    TypeError: Cannot read property 'code' of undefined 
    at /app/node_modules/oauthio/js/main.js:89:80

(Everything works fine if the users signs in and authorizes the app.)

**Comment by bumpmann** [comment]
This issue is related with https://github.com/oauth-io/sdk-node, I added some checks on the provider results and might have fixed this issue. Please try with the latest sdk-node version (0.3.3) and post again on the sdk-node repo if you still have the issue.
