### ISSUE TITLE
Twitter login is not working

### ISSUE THREAD

**Issue by abhishek-kant** [oauth-io/oauth-js#78]
<img width="1280" alt="screen shot 2016-01-19 at 4 01 10 pm" src="https://cloud.githubusercontent.com/assets/1674241/12416264/71211154-bec6-11e5-8632-c7c9e04536f2.png">

**Comment by thyb** [comment]
Twitter seems to have some downtimes with their API: http://status.twitter.com/
I'm not able to reproduce the issue right now (it's working for me), can you confirm it works for you too?
