### ISSUE TITLE
"Me()" function doesn't return full user information when using facebook as a provider and SDK version 2.5

### ISSUE THREAD

**Issue by esteban-filardi** [oauth-io/oauth-js#82]
The "me" function just returns the following information about the user: id, name (not first name and second name), gender and url, even if I have authorized the retrieving of the user e-mail.

I'm not sure if this is the desired behavior because it means that I'd probably have to write custom code for facebook to retrieve the information.

At least the documentation page should be updated because in the example for the javascript SDK, which uses facebook as a provider, indicates that more information should be returned after calling me().

https://oauth.io/getting-started?js

**Comment by bumpmann** [comment]
The me() method is a generic method with the common fields but it must have those fields for a while. You can use get() method if you need more specific fields from facebook.

The description file is here: https://github.com/oauth-io/oauthd/blob/master/providers/facebook/me.js

Feel free to open an issue on https://github.com/oauth-io/oauthd if you still have an issue about providers.
