### ISSUE TITLE
Uncaught TypeError: Cannot read property 'User' of undefined

### ISSUE THREAD

**Issue by nickponline** [oauth-io/oauth-js#89]
I have the following in `index.html`

```
<!DOCTYPE html>
<html lang="en">
<head>
  <script type='text/javascript' src='/oauth.min.js'></script>
</head>
<body>

Hello World.

<script>
  OAuth.initialize('<redacted>');
  OAuth.popup('facebook').done(function(result) {
  }).fail(function (err) { });

 </script>
</body>
</html>
```

and get this error in the browser, any idea what is up?

https://www.dropbox.com/s/xr9xb5vra9dun5l/Screenshot%202016-10-04%2019.10.46.png?dl=0

**Comment by thyb** [comment]
This bug has been introduced in the v0.6.0 few days ago.

I have just published the v0.6.1 which fix it.

Thanks for the report.
